public class BI_PSPB_SupportCenterConstantsCtrl {
    public static String baseImage = System.Label.BI_PSPB_BaseImage;
    public static String supportCenter = System.Label.BI_PSPB_SupportCenter;
    public static String logError = System.Label.BI_PSP_ErrorSeverity;
    public static string errorMsgCaseRecordNotFound = System.Label.BI_PSPB_CaseRecNotFound; //Case record not found
    public static string parameterError = System.Label.BI_PSPB_ErrorParameter; //Error in passing parameter
    public static string error = System.Label.BI_PSPB_ErrorReturning; //Error Returning
    public static String caseRecordTypeName = System.Label.BI_PSPB_SupportCenter;
    public static string errorMsgPatientIdNotFound = System.Label.BI_PSPB_EnrolleeIdNotFound; //Enrollee Id not found
}